/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/axios`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/add-patient`; params?: Router.UnknownInputParams; } | { pathname: `/add-reports`; params?: Router.UnknownInputParams; } | { pathname: `/add-visits`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/otp-verify`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/see-visits`; params?: Router.UnknownInputParams; } | { pathname: `/total-patients`; params?: Router.UnknownInputParams; } | { pathname: `/total-reports`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/axios`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/add-patient`; params?: Router.UnknownOutputParams; } | { pathname: `/add-reports`; params?: Router.UnknownOutputParams; } | { pathname: `/add-visits`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/otp-verify`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/see-visits`; params?: Router.UnknownOutputParams; } | { pathname: `/total-patients`; params?: Router.UnknownOutputParams; } | { pathname: `/total-reports`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/axios${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/add-patient${`?${string}` | `#${string}` | ''}` | `/add-reports${`?${string}` | `#${string}` | ''}` | `/add-visits${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/otp-verify${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/see-visits${`?${string}` | `#${string}` | ''}` | `/total-patients${`?${string}` | `#${string}` | ''}` | `/total-reports${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/axios`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/add-patient`; params?: Router.UnknownInputParams; } | { pathname: `/add-reports`; params?: Router.UnknownInputParams; } | { pathname: `/add-visits`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/otp-verify`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/see-visits`; params?: Router.UnknownInputParams; } | { pathname: `/total-patients`; params?: Router.UnknownInputParams; } | { pathname: `/total-reports`; params?: Router.UnknownInputParams; };
    }
  }
}
